### PR TITLE
Refactoring pot pallet

### PR DESCRIPTION
**Pull request by cocoyoon**
### Summary
- Add test & mock for pot pallet
- 

### Describe your changes
- Change extra field data name from `CollectVote` to `CheckVote`

### Related Issue
#11 

### Checklist before requesting a review
- [ ] I have performed a self-review of my code
- [ ] If it is a core feature, I have added thorough tests.
- [ ] Well documented code
- [ ] `cargo clippy`
- [ ] `cargo-nightly fmt`

### CODE REVIEW

**Comment by cocoyoon** [comment]
@energyGiver @sweatpotato13 리뷰 후 머지 하고 되면 cumulus 쪽 연동을 위해 `master` 로 merge 진행하죠

**Review by sweatpotato13 — APPROVED** [review]
👍

**Review by energyGiver — APPROVED** [review]
reviewed it. Great! But wouldn't it be better to write the comment in English?

**Comment by cocoyoon** [comment]
> reviewed it. Great! And wouldn't it be better to write the comment in English?

Let's talk about it later

**Pull request merged**
